# Generated by Django 4.2.4 on 2023-08-11 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="time_started",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="message",
            name="time_sent",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
