# Generated by Django 4.2.4 on 2023-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="starred",
            field=models.BooleanField(default=False),
        ),
    ]
