# Generated by Django 4.2.4 on 2023-08-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_message_starred"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
