# Generated by Django 4.2.4 on 2023-08-17 21:29

import chat.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sources",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                default=chat.models.get_sources_default,
                size=None,
            ),
        ),
    ]
