
#Create User
POST http://127.0.0.1:8000/chat/signup
Content-Type: application/json 

{"first_name": "kirby", "last_name": "Liao", "username": "kirbyliao@berkeley.edu", "password": "pass"}

###

POST http://127.0.0.1:8000/chat/signup
Content-Type: application/json 

{"first_name": "Lyna", "last_name": "Jiang", "username": "lynajiang@berkeley.edu", "password": "pass"}

###

GET http://127.0.0.1:8000/chat/login
Content-Type: application/json 

{"username": "kirbyliao@berkeley.edu", "password": "pass"}

###

GET http://127.0.0.1:8000/chat/validate
Content-Type: application/json 
Authorization: Token e501334078ab18c3f67cd806333031e7afaca3dc

{}

###

#Create Conversation
POST http://127.0.0.1:8000/chat/course/1
Content-Type: application/json 

{"title": "L", "user": 13, "course": 1}


###


GET http://127.0.0.1:8000/chat/course/1
Content-Type: application/json 

{}

###

#Create Messages
POST http://127.0.0.1:8000/chat/conversation/2
Content-Type: application/json 

{"sender": "user", "content": "test message hi", "conversation": 25}

###

GET http://127.0.0.1:8000/chat/conversation/25
Content-Type: application/json 

{}

###

# POST http://127.0.0.1:8000/chat/course
# Content-type:application/json

# {"title":  "<id of user>", "id": "id"}

# ###

GET http://127.0.0.1:8000/chat/course/1
Content-Type: application/json 




###


