
#Create User
POST http://127.0.0.1:8000/chat/signup
Content-Type: application/json 

{"first_name": "kirby", "last_name": "Liao", "username": "kirby2liao@berkeley.edu", "password": "pass"}

###

POST http://127.0.0.1:8000/chat/signup
Content-Type: application/json 

{"first_name": "Lyna", "last_name": "Jiang", "username": "lynaj2iang@berkeley.edu", "password": "pass"}

###

# Edit user information
PUT http://127.0.0.1:8000/chat/edit_user
Content-Type: application/json
Authorization: Token your_access_token

{
  "first_name": "New First Name",
  "last_name": "New Last Name"
}

###
POST http://127.0.0.1:8000/chat/login
Content-Type: application/json 

{"username": "kirby2liao@berkeley.edu", "password": "pass"}

###

GET http://127.0.0.1:8000/chat/validate
Content-Type: application/json 
Authorization: Token e501334078ab18c3f67cd806333031e7afaca3dc

{}

###

#Create Conversation
POST http://127.0.0.1:8000/chat/course/1
Content-Type: application/json 

{"title": "L", "user": 2, "course": 1}


###


GET http://127.0.0.1:8000/chat/course/1
Content-Type: application/json 

{}

###

#Change conversation title
PUT http://127.0.0.1:8000/chat/conversation/1
Content-Type: application/json

{"title": "newTitle"}

###

#Delete Conversation
DELETE http://127.0.0.1:8000/chat/conversation/1
Content-Type: application/json

{}

###

#Create Messages
POST http://127.0.0.1:8000/chat/conversation/2
Content-Type: application/json 

{"sender": "user", "content": "test message hi", "conversation": 1}

###

GET http://127.0.0.1:8000/chat/conversation/1
Content-Type: application/json 

{}

###


#Star a message
PUT http://127.0.0.1:8000/chat/message/star/1
Content-Type: application/json
Authorization: Token your_access_token

{"starred": true}

###

#Unstar a message
PUT http://127.0.0.1:8000/chat/message/star/1
#path: messages/messageId/star
Content-Type: application/json
Authorization: Token your_access_token

{"starred": false}

###

#Fetch source information
GET http://127.0.0.1:8000/chat/source/1
Content-Type: application/json
Authorization: Token your_access_token

{}

###

# POST http://127.0.0.1:8000/chat/course
# Content-type:application/json

# {"title":  "<id of user>", "id": "id"}

# ###

GET http://127.0.0.1:8000/chat/course/1
Content-Type: application/json 




###


